/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/favicon-96x96.png",
        "actionBtn": {
          "type": "primary"
        }
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-a0e7e51a",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "345345",
          "slug": "_345345"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ]
  }
}