/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Nulls world",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "https://cdn.bootcdn.net/ajax/libs/animate.css/4.1.1/animate.min.css"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/favicon-96x96.png",
        "actionBtn": {
          "type": "primary"
        },
        "banner": {
          "leading": "The standard for secure blockchain applications",
          "description": "OpenZeppelin provides security products to build,automate,and operate decentralized applications. We also protect leading organizations by performing security audits on their systems and products."
        },
        "section2": {
          "subLeading": "The world’s leading projects trust OpenZeppelin",
          "heading": "The challenges of building decentralized applications",
          "challenges": [
            {
              "leading": "Security",
              "des": "Economies in which software powers real money are exposed to hacks and attacks."
            },
            {
              "leading": "Developer Experience",
              "des": "Lack of proper development and testing tools increases programming errors greatly."
            },
            {
              "leading": "Operations",
              "des": "It’s difficult to manage and fix problems in decentralized systems once they're deployed."
            }
          ]
        },
        "section3": {
          "leading": "Your blueprint for decentralized systems",
          "subLeading": "Reduce barriers to entry by securely implementing blockchain-based technologies, using standard developer tools and platforms.",
          "productCards": [
            {
              "cardImg": "/oz_contracts_blue.svg",
              "subLeading": "A library of modular, reusable, secure smart contracts for the Ethereum network, written in Solidity.",
              "desList": [
                "Leverage standard, tested, and community-reviewed contracts.",
                "Most popular library in the industry.",
                "Learn from best practices adopted by the ecosystem.",
                "Reduce your attack surface by reusing audited code."
              ],
              "actions": [
                {
                  "text": "visit site",
                  "link:\"http://www.baidu.com\"": null
                },
                {
                  "text": "go to docs",
                  "link:\"http://www.baidu.com\"": null
                }
              ]
            },
            {
              "cardImg": "/oz_defender_blue.svg",
              "subLeading": "A platform to automate Ethereum operations and deliver high-quality products faster.",
              "desList": [
                "Automate your smart contract administration with a clean UI.",
                "Build with private and secure transaction infrastructure.",
                "Create automated scripts to call your smart contracts.",
                "Quickly implement security best practices."
              ],
              "actions": [
                {
                  "text": "visit site",
                  "link:\"http://www.baidu.com\"": null
                },
                {
                  "text": "go to docs",
                  "link:\"http://www.baidu.com\"": null
                }
              ]
            }
          ]
        },
        "section4": {
          "quote": "I have a very high opinion of the OpenZeppelin team and their work",
          "quoteAuthor": "Brendan Eich",
          "quoteAuthorDes": "Founder of Mozilla and Brave, Javascript creator."
        },
        "section5": {
          "secureHeading": "In-depth security audits",
          "secureDes": "In an economy where software code powers real money, security is a top priority. We specialize in auditing in high-impact decentralized systems.",
          "secureActicon": {
            "text": "learn more",
            "link": ""
          },
          "building": "Start building",
          "buildingSub": "Check out our resources for beginner and experienced smart contracts and blockchain developers.",
          "buildingGuide": [
            {
              "title": "Docs",
              "link": "#",
              "des": "Learn everything you need to develop blockchain applications through a complete set of guides and tutorials."
            },
            {
              "title": "Forum",
              "link": "#",
              "des": "Connect with experts, beginners and enthusiasts and discuss about blockchain development, security, design patterns and best practices."
            },
            {
              "title": "Ethernaut",
              "link": "#",
              "des": "A Web3/Solidity based wargame played in Ethereum where each level is a smart contract that needs to be hacked."
            }
          ]
        }
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-0f62a824",
      "path": "/"
    }
  ],
  "themeConfig": {
    "logo": "/oz_main_color.svg",
    "nav": [
      {
        "text": "Products",
        "custom": true,
        "items": [
          {
            "text": "Contracts",
            "des": "A Solidity library of reusable and secure smart contracts",
            "link": "/contracts"
          },
          {
            "text": "Defender",
            "des": "A platform to automate smart contract operations",
            "link": "/defender"
          }
        ]
      },
      {
        "text": "Security Audits",
        "link": "/secure"
      },
      {
        "text": "Learn",
        "items": [
          {
            "text": "Docs",
            "link": "/docs"
          },
          {
            "text": "Community",
            "link": "/community"
          },
          {
            "text": "Github",
            "link": "/github"
          }
        ]
      },
      {
        "text": "Company",
        "link": "/company"
      },
      {
        "text": "News & Events",
        "link": "/news"
      }
    ],
    "sidebar": {
      "sideBarOfLearn": [
        {
          "text": "Community Forum",
          "link": "#"
        },
        {
          "text": "Docs",
          "link": "#"
        },
        {
          "text": "Ethernaut",
          "link": "#"
        }
      ],
      "sideBarOfCompany": [
        {
          "text": "About us",
          "link": "#"
        },
        {
          "text": "Jobs",
          "link": "#"
        },
        {
          "text": "Github",
          "link": "#"
        },
        {
          "text": "Blog",
          "link": "#"
        }
      ]
    },
    "footer": [
      {
        "title": "Products",
        "content": [
          {
            "text": "Contracts",
            "link": "#"
          },
          {
            "text": "Defender",
            "link": "#"
          }
        ]
      },
      {
        "title": "Security",
        "content": [
          {
            "text": "Audits",
            "link": "#"
          },
          {
            "text": "Request a security audit",
            "link": "#"
          }
        ]
      },
      {
        "title": "Learn",
        "content": [
          {
            "text": "Docs",
            "link": "#"
          },
          {
            "text": "Community Forum",
            "link": "#"
          },
          {
            "text": "Ethernaut",
            "link": "#"
          }
        ]
      },
      {
        "title": "Company",
        "content": [
          {
            "text": "About Us",
            "link": "#"
          },
          {
            "text": "Jobs",
            "link": "#"
          },
          {
            "text": "Github",
            "link": "#"
          },
          {
            "text": "Twitter",
            "link": "#"
          },
          {
            "text": "Discord",
            "link": "#"
          },
          {
            "text": "Logo Kit",
            "link": "#"
          }
        ]
      }
    ]
  }
}